spring:
  profiles:
    active: local
    include: oauth

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

logging:
  level:
    org.hibernate.SQL: debug
    com.yoonji.adminproject: debug