spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(CV80/wTei58S3dIzgBOd4zSc0cuBzDEvW+S8YJelm5rVAQlhS//PwgOuQkOC6uxGtglb2RBT0x5KIzxkS2Mw7I26V4cP85Llioa98YALvfJGD0QW5O0DjQ==)
            client-secret: ENC(B53Uv0MsO6+j8Vze+pUy4psAIW7CbZEaR267UuRU39biqm+N6NrVZ7dGAAUBNsgE)
            scope: profile,email
          naver:
            client-id: ENC(B1Un1vE3iLQ/6sWost+7I/NIXS2YrEIpgPzeiUSEDLg=)
            client-secret: ENC(MJiLEH4GFbppsrr/anoHb+B7EAjhhG5B)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email,name,profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response