spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_project?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    include: oauth

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug
  com.yoonji.adminproject: debug